# Generated by Django 3.1 on 2020-10-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iTeam', '0001_initial'),
    ]

    operations = [
    ]
