# Generated by Django 3.1 on 2020-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iTeam', '0003_researcher_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='researcher', to='iTeam.Researcher'),
        ),
    ]
