# Generated by Django 3.1 on 2020-10-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iTeam', '0004_auto_20201016_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='researchers', to='iTeam.Researcher'),
        ),
    ]
