# Generated by Django 3.1 on 2020-10-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iTeam', '0005_auto_20201016_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_project',
            field=models.FileField(blank=True, upload_to='media/projects'),
        ),
    ]
